let header = document.querySelector("header")
window.addEventListener("scroll",()=>{
    if(window.scrollY>=100)
    {
        header.classList.add("headerScroll")
    }
    else 
    {
        header.classList.remove("headerScroll")
    }
})
$('#testimonial-slider').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:2000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})
$('#blog-slider').owlCarousel({
    loop:true,
    margin:20,
    nav:true,
    autoplay:true,
    autoplayTimeout:2000,
    autoplayHoverPause:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:4
        }
    }
})